### ISSUE TITLE
Invite fork owners

### ISSUE THREAD

**Issue by petri** [beanstalkd/pybeanstalk#11]
In addition to people already here, there are forks by @dustin, @pragnesh, @AlekSi, @rubenk, @gerry, @jasiek @labjack, @kaulie, @wuguobao and @ZoomQuiet.

This issue is an attempt to reach them via GitHub mentions and let them know that pybeanstalk has been transferred to the beanstalkd GitHub organization, and, that issues and pull requests are most welcome!

**Please, if your GitHub username is on the above list and you see this, comment on this issue and let us know what you'd like to see happen to pybeanstalk - and whether you'd perhaps even like to join the GitHub organization to help improve pybeanstalk.**

**Comment by AlekSi** [comment]
Hi. Personally I moved to other things. Feel free to incorporate some code from my fork.

**Comment by dustin** [comment]
I've also not used any of this in a while.  Let me know if I can help with
any extraction of things that seem useful (can't quite remember what I did).

**Comment by jasiek** [comment]
I just had this one PR and I'll kill the fork when merged.

**Comment by gerry** [comment]
I also just had the one PR and have since moved on.

**Comment by petri** [comment]
Thanks for responding guys!

**Comment by rubenk** [comment]
I've just killed my fork. I still have some local changes and will check if there's anything that I can put in a PR.

**Comment by petri** [comment]
@gerry, @jasiek the pull requests have been merged. @rubenk did you have a chance to see if you can find anything?

**Comment by petri** [comment]
FYI, there is now a PyPI release with all known issues have now fixed and all pull requests merged.

**Comment by rubenk** [comment]
@petri not yet, but I'll open pull requests with any fixes I have.

**Comment by petri** [comment]
Done.
