### ISSUE TITLE
Document how to run tests (fix tests)

### ISSUE THREAD

**Issue by petri** [beanstalkd/pybeanstalk#12]
@sophacles , @jamescasbon,

Could you please help in documenting how the tests are to be run? I just tried to run the tests by going to the tests directory and running nosetests. It looks like that is the way to go, but I got some errors.

I am not really familiar with nose, but taking a look at some of the files, I understand some of the tests require a live beanstalkd server (or more than one server). That caused at least some of the errors, perhaps even all of them. 

Perhaps we could split the tests into three groups (at least in the documentation):

* those that require no live server
* those that need one server
* those that need more than one

So we could ask pull request submitters to provide and run tests without forcing them to set up multiple beanstalk servers just because some tests require them.

This should be easy by using nose to run just some of the tests, either manually by module or test name, or perhaps using some nose-specific criteria for grouping?

**Comment by petri** [comment]
I would also like to be able to run the tests prior to merging the pull requests #2 and #3 - they seem straightforward enough, but nevertheless...

**Comment by sophacles** [comment]
It should just work with nosetests being run from the test directory IIRC.

The `setup` and `teardown` functions in each test file are fun immediately prior to and immediately after each test funciton, and handle the process wrangling of the beanstalk server(s) for testing.

The `tests.cfg` file has some settings that are helpful - e.g. `BPATH` and `BEANSTALKD` which are combined to tell the tests what the executable for beanstalkd is. If you have it in a location other than `/usr/local/bin` you'll need to either move it, or update the settings in the `tests.cfg` file.

**Comment by petri** [comment]
Thanks @sophacles. I managed to run the tests, which produce the following output a number several times:

```Exception ServerInUse: ServerInUse('AsyncServerConn(127.0.0.1:11303#[Open][Waiting]) is currently in use!', <0x139986747569216 AsyncServerConn(127.0.0.1:11303#[Open][Waiting])>) in method __del__ of <beanstalk.job.Job object at 0x0000000001ea3298> ignored```

Any thoughts?

**Comment by petri** [comment]
I added a wiki page on how to run tests. Closing.
