### ISSUE TITLE
Fix MultiServerConn (tests?)

### ISSUE THREAD

**Issue by petri** [beanstalkd/pybeanstalk#13]
The test ```test_MultiServerConn.py``` produces the following output a number several times (on Debian stable, newest Python 2.x.x with beanstalkd from debian pkg):

```Exception ServerInUse: ServerInUse('AsyncServerConn(127.0.0.1:11303#[Open][Waiting]) is currently in use!', <0x139986747569216 AsyncServerConn(127.0.0.1:11303#[Open][Waiting])>) in method __del__ of <beanstalk.job.Job object at 0x0000000001ea3298> ignored```

It's always the connection to 11303, with a different Job object each time.

There's also one error and one failure:

```
ERROR: test_MultiServerConn.test_tube_operations
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pythonapps/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/media/psf/Code/thirdparty/pybeanstalk/tests/test_MultiServerConn.py", line 296, in test_tube_operations
    "Was expecting %s, got %s" % (expecting,
NameError: global name 'expecting' is not defined
```

```
======================================================================
FAIL: test_MultiServerConn.test_reserve_timeout_works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pythonapps/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/media/psf/Code/thirdparty/pybeanstalk/tests/test_MultiServerConn.py", line 323, in test_reserve_timeout_works
    assert conn.stats()['data']['current-jobs-ready'] == 0, "The server is not empty "\
AssertionError: The server is not empty of jobs so test behaviour cannot be guaranteed.  Bailing out.
```

**Comment by petri** [comment]
@sophacles could you take a quick look and suggest what to do with these?

**Comment by petri** [comment]
Ok I figured out how the test should work and fixed it. @mahmoudimus you may want to check my fix to make sure the test is doing what you originally envisioned it should. 

For what it's worth, I am surprised at the way the ServerPool stats call apparently works (just hits a random server rather than somehow merging the stats, for example)..

**Comment by mahmoudimus** [comment]
@petri will take a look re: your fix. I wonder if it makes sense to create a new issue to port to pytest and tox so we can establish a more modern development/testing feedback cycle.

**Comment by sophacles** [comment]
+1 on tox. Have no strong opinions on pytest vs nose vs raw unittest, but tox is a lifesaver.

**Comment by petri** [comment]
I would probably be +1 on both; I use pytest already to test the Twisted app I am developing on top of pybeanstalk (FWIW, [here's a blog post](https://koodaamo.wordpress.com/2015/07/09/py-test-subprocess-fixture-callables-for-testing-twisted-apps/) that I wrote on that). The same blog also has a comparison of nose and pytest.
