### ISSUE TITLE
Job should not try to delete itself from server upon garbage collection

### ISSUE THREAD

**Issue by petri** [beanstalkd/pybeanstalk#21]
Special method __del__ is called by Python when the last reference of the item is being destroyed. See https://docs.python.org/2/reference/datamodel.html#object.__del__.

Given that, I don't understand why there's __del__ implementation at https://github.com/beanstalkd/pybeanstalk/blob/master/beanstalk/job.py#L65-L66 that calls self.Finish, in other words the Job is trying to delete itself from beanstalk server???

I can understand someone might somewhat mistakenly try to support deleting a job by ```del job```, but this is dangerous: an application may have more references hanging around when del is called, and on the other hand, there are cases where the reference ends up destroyed inadvertently.

Apparently this has been [noticed before](https://github.com/beanstalkd/pybeanstalk/blob/880ddb4566fd68bf93161cfa86df379afa3314e9/tests/test_MultiServerConn.py#L219) as well...

 I am not aware of pybeanstalk using the ```__del__``` implementation internally. I will remove the ```__del__``` implementation unless someone objects for a good reason.

**Comment by sophacles** [comment]
The idea was to cleanup a job reservation in all cases, instead of having it timeout. I certainly wouldn't do this anymore... In retrospect it was probably a dumb idea.

 +1 on this.
