### ISSUE TITLE
Set up CI for pybeanstalk

### ISSUE THREAD

**Issue by petri** [beanstalkd/pybeanstalk#24]
How about https://travis-ci.org ? @kr, to set it up for pybeanstalk, Travis CI needs permission to access beanstalk organization repositories; hope you're ok with that.

**Comment by petri** [comment]
See https://github.com/travis-ci/travis-ci/issues/4320

**Comment by kr** [comment]
Yup, fine by me.

**Comment by petri** [comment]
Done, Python 2.7 and PyPY runs passing.
