### ISSUE TITLE
ImportError: No module named 'serverconn'

### ISSUE THREAD

**Issue by EpocDotFr** [beanstalkd/pybeanstalk#25]
- Python 3.5.1
- Windows 7 & 10 (but I think this is reproductible on any Windows version)

When importing the `pybeanstalk` package in any possible manner, the following exception is raised:

```
Traceback (most recent call last):
  File "local_server.py", line 1, in <module>
    from war import app
  File "C:\war\war.py", line 3, in <module>
    from beanstalk import job
  File "C:\{SomeFolders}\Python35\lib\site-packages\beanstalk\__init__.py", line 1, in <module>
    import serverconn
ImportError: No module named 'serverconn'
```

By "any possible manner", I'm mean I tried the following `import` statements in my `C:\war\war.py` file:

```python
import beanstalk
from beanstalk import job, serverconn
from beanstalk import serverconn
```

I don't understand what is the issue. Maybe this is related to relative imports in Python 3?

**Comment by petri** [comment]
Python 3 is not supported. Feel free to open an issue for that. No guarantees that anyone will have time to work on that though. Updating this package to support Python3 is not trivial.

**Comment by EpocDotFr** [comment]
I found an alternative package, compatible with Python 3, [here](https://github.com/menezes-/pystalkd) if this can help anyone.
