### ISSUE TITLE
package for (first) release on pypi

### ISSUE THREAD

**Issue by petri** [beanstalkd/pybeanstalk#6]
update package structure, switch to setuptools, etc.

**Comment by petri** [comment]
Note: This should probably be done as the last step of the milestone.

**Comment by petri** [comment]
branch added: https://github.com/beanstalkd/pybeanstalk/tree/setuptools_pkging

**Comment by petri** [comment]
I am going to make an initial PyPI release soon. @mahmoudimus, I assume you should be added to the list of contributors in docs/CREDITS, please add yourself or let me know what you've done and I'll add you there.

**Comment by petri** [comment]
@sophacles, I understand the versioning has followed that of beanstalkd in the past. 

So perhaps the version should at least be bumped to 1.10.1 that is the current beanstalk (1.10-1 actually but I am not sure the dash is recommeded for a Python package version). I am developing with that on Debian so we know it works.

On the other hand, how do we then upgrade the version of this package? I don't really see how keeping the version sync is feasible.

**Comment by petri** [comment]
Ok unless anyone objects, I am going to merge the setuptools_pkging branch, make sure the tests pass and then make the first release to PyPI to get some exposure. I would really appreciate if someone could take a good look at #13 to get rid of that last remaining (as of now) bug.

**Comment by petri** [comment]
All milestone issues closed apart from this. Hurrah! ;)

**Comment by sophacles** [comment]
@petri I think the python package version following beanstalkd version was a mistake. At the time it made sense because @kr was pushing out new releases pretty often. A new independent versioning should probably be done though.

**Comment by petri** [comment]
Ok. Perhaps we can start from 1.0rc0 (using the release candidate postfix as suggested by PEP0440) and then release 1.0 when any surprises have been handled.

**Comment by sophacles** [comment]
I think that's a good plan. :+1:

**Comment by petri** [comment]
released on pypi, closing
