### ISSUE TITLE
Transfer to GitHub Beanstalkd organization

### ISSUE THREAD

**Issue by petri** [beanstalkd/pybeanstalk#9]
Looks like this repository is not that much maintained, and there are many forks with some improvements.

It would be good if we could roll the pybeanstalk improvements into one "canonical" repository and publish the package on PyPI. 

@sophacles , would it be ok for you to move the repository to https://github.com/beanstalkd and encourage forkers maybe join the organization as well? I could ask Keith Rarick @kr (author of beanstalkd) if it would be ok for him.

**Comment by kr** [comment]
Fine by me.

**Comment by sophacles** [comment]
@petri I like this idea - I want to double check that @mahmoudimus doesn't object, as he is a collaborator on this project and should have the opportunity to vote as well. Let's give it a couple days for him to have the opportunity to weigh in, then go forward with this.

**Comment by mahmoudimus** [comment]
I am OK with this.

On Tuesday, June 30, 2015, Erich Heine <notifications@github.com> wrote:

> @petri <https://github.com/petri> I like this idea - I want to double
> check that @mahmoudimus <https://github.com/mahmoudimus> doesn't object,
> as he is a collaborator on this project and should have the opportunity to
> vote as well. Let's give it a couple days for him to have the opportunity
> to weigh in, then go forward with this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sophacles/pybeanstalk/issues/9#issuecomment-117237890>
> .
>


-- 
- Mahmoud

**Comment by petri** [comment]
Ok I asked @sophacles to do the transfer. Once it's done, @kr please give him, @mahmoudimus and myself admin rights to the transferred repository.

I will then try to find some time to get other forkers on board to submit issues and pull requests with the common goal of making a pypi release with any fixes and generally useful improvements that the forks may have.

**Comment by mahmoudimus** [comment]
Thanks for taking the lead on this Petri!

- Mahmoud

On Tue, Jun 30, 2015 at 10:33 AM, Petri Savolainen <notifications@github.com

**Comment by sophacles** [comment]
Ok, the transfer of ownership to the beanstalkd org is done.

Thanks @petri for getting this going!

**Comment by petri** [comment]
The repository has been transferred (thanks @kr and @sophacles). I suggest we keep this issue open a while longer to have a place for any comments about how to proceed etc. that might not merit their own issue. 

For one such thing, I moved the old Google Code wiki pages here, with minor edits to bring them up to date a bit, and moved the reference to the old location to the new History page.

**Comment by petri** [comment]
Is it ok for everyone that we add fork authors to this organization & give them access to this pybeanstalk repo? After asking if they want to, of course ;-)

I would also like to suggest that any pull requests be reviewed by a minimum of two team members before accepting them, just 'cause two pairs of eyes on new stuff might better catch things that one does not.

**Comment by kr** [comment]
Sure, it's ok with me.

**Comment by petri** [comment]
@sophacles & @mahmoudimus, do you have any time to review any of the pull requests I've made and/or commented on? 

If not, is it ok for you if I go and merge them myself (I promise to fix any bugs my code might introduce)?

**Comment by sophacles** [comment]
@petri I took a quick look, Anything I didn't comment on seems OK to me.

As for overall handling - I think you should feel free to commit as you think things are ready. I'm glad to look at stuff when time is available for me, but that won't be often. You are actually using this code and making the effort to update/improve it, so do what's needed to make it work well for you (and the others actively using it of course) :)

**Comment by petri** [comment]
Thanks @sophacles. All code issues are closed, the tests pass (with some Twisted tests too), pull requests have been merged and the setuptools packaging branch works. So I am going to merge the branch and release the package to PyPI (#6) tomorrow unless something unexpected pops up.

**Comment by petri** [comment]
There is now a PyPI release, 1.0rc1

**Comment by petri** [comment]
Done.
